version: "3"
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: yarn dev
    tty:
      true
